version: '3'

services:
  spark-master:
    image: bitnami/spark:3.5
    volumes:
      - ./spark-app:/spark-app 
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PIP_PACKAGES=numpy scipy redis
    command: /bin/bash -c "pip install --quiet $$PIP_PACKAGES && /opt/bitnami/scripts/spark/run.sh"
    ports:
      - "8080:8080" 
      - "7077:7077" 

  spark-worker-1:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - PIP_PACKAGES=numpy scipy redis
    command: /bin/bash -c "pip install --quiet $$PIP_PACKAGES && /opt/bitnami/scripts/spark/run.sh"
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - PIP_PACKAGES=numpy scipy redis
    command: /bin/bash -c "pip install --quiet $$PIP_PACKAGES && /opt/bitnami/scripts/spark/run.sh"
    depends_on:
      - spark-master

  spark-worker-3:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - PIP_PACKAGES=numpy scipy redis
    command: /bin/bash -c "pip install --quiet $$PIP_PACKAGES && /opt/bitnami/scripts/spark/run.sh"
    depends_on:
      - spark-master

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"  
      - "9093:9093" 
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data:/bitnami/kafka

  data-generator:
    build: 
      context: ./data_generator
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=streaming_data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: ./visualization
    ports:
      - "5000:5000"
    depends_on:
      - redis

volumes:
  kafka_data:


networks:
  default:
    name: kafka-spark-net
    driver: bridge